name: data_request
on: [push]
jobs:
  generate-data:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:latest
    steps:
      - uses: actions/checkout@v2
        
 
      - uses: r-lib/actions/setup-r@master
      
      - name: Setup dependencies
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'      
        
      - name: Generate data
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          Rscript data_pipe.R
      
                 
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push
