name: data-extraction-api
on: [push]
jobs:
   run:
     runs-on: [ubuntu-latest]
     container: 
     steps:
        - uses: 
        - name: Setup R
          uses: r-lib/actions/setup-r@master
          
        - name: Setup Dependencies
          run: |
            R -e 'install.packages("renv")'
            R -e 'renv::restore()'
            
        - name: Run Script Data
          env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
         run: |
         R -e 'renv::run("data_pipe.R")'
         
         git-push data.final.RDS
         
         
